fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
            address:        'maciejborzymowski1@gmail.com'
            sender_name:    'Demo Registration'
    registration:
            confirmation:
                template:   '@FOSUser/Registration/email.txt.twig'
                enabled:    true
                from_email:
                        address:        'maciejborzymowski1@gmail.com'
                        sender_name:    'Demo Registration'
    service:
            mailer: fos_user.mailer.twig_swift