swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode: "%mailer_auth_mode%"
    port:       465
    spool:     { type: memory }
    stream_options:
          ssl:
            allow_self_signed: true
            verify_peer: false
parameters:
    mailer_auth_mode: login
    mailer_encryption: ssl
    mailer_host: smtp.gmail.com
    mailer_transport: smtp
    mailer_user: maciejborzymowskionlinestore@gmail.com
    mailer_password: onlinestore1