fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
index:
    path: /
    controller: App\Controller\ProductController::getProducts

homepage:
    path: /product/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true

