
index:
    path: /
    controller: App\Controller\ProductController::getProducts

homepage:
    path: /product/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true

